services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  app:
    image: thiennq810/deployment_pipeline
    container_name: pipeline_example
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
